#!/usr/bin/env python3
"""
Config Manager – Backup Engine
Uses Netmiko to connect to network devices and retrieve running configurations.

Usage:
    python3 backup.py --ip 192.168.1.1 --vendor cisco_ios \
        --user admin --pass secret --port 22 --out /opt/config-backups/Router1/2026-06-20_0100.cfg

Requirements:
    pip3 install netmiko
"""

import argparse
import os
import sys
import traceback
from pathlib import Path

try:
    from netmiko import ConnectHandler
    from netmiko.exceptions import (
        NetmikoTimeoutException,
        NetmikoAuthenticationException,
    )
except ImportError:
    print("ERROR: netmiko is not installed. Run: pip3 install netmiko", file=sys.stderr)
    sys.exit(1)


VENDOR_MAP = {
    "cisco_ios": {
        "device_type": "cisco_ios",
        "commands": ["show running-config"],
        "strip_headers": True,
    },
    "cisco_nxos": {
        "device_type": "cisco_nxos",
        "commands": ["show running-config"],
        "strip_headers": False,
    },
    "fortinet": {
        "device_type": "fortinet",
        "commands": ["show full-configuration"],
        "strip_headers": False,
    },
    "mikrotik": {
        "device_type": "mikrotik_routeros",
        "commands": ["/export"],
        "strip_headers": True,   # MikroTik also adds a timestamp line
    },
    "juniper": {
        "device_type": "juniper_junos",
        "commands": ["show configuration"],
        "strip_headers": False,
    },
}

# Lines whose content changes every run but carry no config meaning.
# Stripping them prevents false "config changed" detections.
NOISE_PATTERNS = [
    "Building configuration",
    "Current configuration",
    "Load for five",
    "Time source is",
    "! Last configuration change",
    "! NVRAM config last updated",
    "# generated by",          # MikroTik timestamp line
    "# by RouterOS",           # MikroTik version line that may change
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Config Manager – Device Backup")
    parser.add_argument("--ip",      required=True,  help="Device IP address")
    parser.add_argument("--vendor",  required=True,  choices=list(VENDOR_MAP.keys()))
    parser.add_argument("--user",    required=True,  help="SSH username")
    parser.add_argument("--pass",    required=True,  dest="password", help="SSH password")
    parser.add_argument("--port",    type=int, default=22, help="SSH port (default 22)")
    parser.add_argument("--out",     required=True,  help="Output file path")
    parser.add_argument("--timeout", type=int, default=30, help="Connection timeout seconds")
    return parser.parse_args()


def ensure_dir(filepath: str) -> None:
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)


def strip_noise(output: str) -> str:
    """
    Remove lines that change on every backup but carry no config meaning.
    This prevents false 'config changed' detections caused by timestamps
    and counters that Cisco/MikroTik embed in their output.
    """
    lines = output.splitlines()
    result = []
    for line in lines:
        stripped = line.strip()
        if any(stripped.startswith(p) or p in stripped for p in NOISE_PATTERNS):
            continue
        result.append(line)
    return "\n".join(result)


def backup_device(args: argparse.Namespace) -> str:
    vendor_cfg = VENDOR_MAP[args.vendor]

    device_params = {
        "device_type": vendor_cfg["device_type"],
        "host":        args.ip,
        "username":    args.user,
        "password":    args.password,
        "port":        args.port,
        "timeout":     args.timeout,
        "conn_timeout": args.timeout,
        "session_log": None,
    }

    if args.vendor == "juniper":
        device_params["fast_cli"] = False

    print(f"[INFO] Connecting to {args.ip} ({args.vendor}) on port {args.port}...")

    with ConnectHandler(**device_params) as conn:
        print(f"[INFO] Connected. Retrieving configuration...")

        full_output = []
        for cmd in vendor_cfg["commands"]:
            print(f"[INFO] Running: {cmd}")
            if args.vendor == "cisco_ios":
                output = conn.send_command(
                    cmd,
                    expect_string=r"#",
                    read_timeout=60,
                    strip_prompt=True,
                    strip_command=True,
                )
            else:
                output = conn.send_command(
                    cmd,
                    read_timeout=60,
                    strip_prompt=True,
                    strip_command=True,
                )
            full_output.append(output)

    config_text = "\n".join(full_output)

    # Always strip noise lines — never write timestamps into the config file
    config_text = strip_noise(config_text)

    return config_text.strip()


def main() -> None:
    args = parse_args()

    try:
        ensure_dir(args.out)
        config_text = backup_device(args)

        if not config_text:
            print("[ERROR] Empty configuration received.", file=sys.stderr)
            sys.exit(1)

        # Write ONLY the device config — no timestamps, no metadata headers.
        # The backup filename already encodes the date/time.
        # Adding any time-varying content here would cause false change detections.
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(config_text)
            f.write("\n")

        size_kb = os.path.getsize(args.out) / 1024
        print(f"[OK] Backup saved to: {args.out} ({size_kb:.1f} KB)")
        sys.exit(0)

    except NetmikoAuthenticationException as e:
        print(f"[ERROR] Authentication failed: {e}", file=sys.stderr)
        sys.exit(1)

    except NetmikoTimeoutException as e:
        print(f"[ERROR] Connection timed out: {e}", file=sys.stderr)
        sys.exit(1)

    except Exception as e:
        print(f"[ERROR] Unexpected error: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
